version: "3.8"

services:
  backend:
    build: ./backend
    image: ml-contact-app/backend:latest
    networks:
      - ml-contact
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    networks:
      - ml-contact
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/frontend:/usr/share/nginx/html
      - ./null:/etc/nginx/conf.d:ro
      - ../ssl/certs:/etc/ssl/certs:ro
      - ../ssl/private:/etc/ssl/private:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - backend

networks:
  ml-contact:
    driver: overlay
