version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ml-contact-app/backend:latest
    networks:
      - ml-contact
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    networks:
      - ml-contact
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/frontend:/usr/share/nginx/html
      - ./nginx/certs:/etc/ssl/certs:ro
      - ./nginx/private:/etc/ssl/private:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - backend

networks:
  ml-contact:
    driver: overlay
